import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Exact Stitch design tokens
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "on-secondary-container": "#007232",
        "outline": "#777587",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "primary-container": "#4f46e5",
        "surface-container-high": "#dce9ff",
        "inverse-surface": "#213145",
        "secondary-container": "#5dfd8a",
        "surface-container-highest": "#d3e4fe",
        "on-primary-fixed-variant": "#3323cc",
        "on-primary-container": "#dad7ff",
        "on-surface": "#0b1c30",
        "surface-tint": "#4d44e3",
        "surface": "#f8f9ff",
        "secondary-fixed": "#66ff8e",
        "tertiary": "#7e3000",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#464555",
        "surface-container-low": "#eff4ff",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff",
        "primary": "#3525cd",
        "on-error": "#ffffff",
        "surface-variant": "#d3e4fe",
        "inverse-primary": "#c3c0ff",
        "background": "#f8f9ff",
        "on-primary-fixed": "#0f0069",
        "secondary": "#006d2f",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#3de273",
        "primary-fixed": "#e2dfff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "outline-variant": "#c7c4d8",
        "tertiary-container": "#a44100",
        "whatsapp-green": "#25D366",
        "whatsapp-dark": "#1DA851",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "container-max": "1280px",
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "mono-code": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      boxShadow: {
        "card": "0 2px 4px rgba(79,70,229,0.04)",
        "card-hover": "0 4px 8px rgba(79,70,229,0.08)",
        "ambient": "0 24px 48px -12px rgba(79,70,229,0.08), 0 12px 24px -8px rgba(79,70,229,0.04)",
        "primary-sm": "0 2px 4px rgba(79,70,229,0.12)",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
